version: '3.9'
services:
  nginx:
    build: .
    image: interstellar-proxy-nginx
    container_name: interstellar-nginx
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
