services:
  - type: web
    name: transparent-proxy
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: node server/server.js
    envVars:
      - key: UV_DEBUG
        value: "false"
